### ISSUE TITLE
Error in BN propagation result?

### ISSUE THREAD

**Issue by piedenis** [PyOpenPNL/PyOpenPNL#1]
I think that I found an error on https://oshearesearch.com/2016/02/02/bayesian-network-inference-with-pyopenpnl/
If I understand well, the simple_bnet.py program gives
    P(W|C=0) =  0.211503
This is WRONG, I'm afraid! My Lea module (Python) gives
    P(W|C=0) =  0.549
a value in line with the paper "Belief Propagation in Fuzzy Bayesian Networks: A Worked Example"
by Christopher Fogelberg (http://syntilect.com/cgf/_media/pubs:files:fbn-example.pdf?id=pubs%3Afbn-example) - see section 4.1. So, provided that these two independent references are right, there's something to correct, at least in the afore-mentioned page (I didn't test simple_bnet.py myself).

**Comment by kkarrancsu** [comment]
Hi @piedenis , thanks for your note.  You are correct, I have fixed the example.  The issue was with how the probability tables were being entered into the problem.
